// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gorpsgen;

namespace gorpsgen.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20181212222108_ArchetypeTables")]
    partial class ArchetypeTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("gorpsgen.Models.Archetype", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseDexterity");

                    b.Property<int>("BaseHealth");

                    b.Property<int>("BaseIntelligence");

                    b.Property<int>("BaseStrength");

                    b.Property<int>("CombatRating");

                    b.Property<int>("MagicRating");

                    b.Property<string>("Name");

                    b.Property<int>("StealthRating");

                    b.HasKey("ID");

                    b.ToTable("Archetypes");

                    b.HasData(
                        new { ID = 1, BaseDexterity = 11, BaseHealth = 12, BaseIntelligence = 9, BaseStrength = 14, CombatRating = 7, MagicRating = 0, Name = "Warrior", StealthRating = 0 },
                        new { ID = 2, BaseDexterity = 11, BaseHealth = 10, BaseIntelligence = 14, BaseStrength = 9, CombatRating = 0, MagicRating = 7, Name = "Mage", StealthRating = 0 },
                        new { ID = 3, BaseDexterity = 13, BaseHealth = 10, BaseIntelligence = 11, BaseStrength = 10, CombatRating = 0, MagicRating = 0, Name = "Thief", StealthRating = 7 },
                        new { ID = 4, BaseDexterity = 10, BaseHealth = 10, BaseIntelligence = 10, BaseStrength = 10, CombatRating = 0, MagicRating = 0, Name = "Peasant", StealthRating = 0 }
                    );
                });

            modelBuilder.Entity("gorpsgen.Models.ArchetypeSkill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArchetypeID");

                    b.Property<int>("SkillID");

                    b.HasKey("ID");

                    b.HasIndex("ArchetypeID");

                    b.HasIndex("SkillID");

                    b.ToTable("ArchetypeSkills");

                    b.HasData(
                        new { ID = 1, ArchetypeID = 1, SkillID = 1 },
                        new { ID = 2, ArchetypeID = 1, SkillID = 2 },
                        new { ID = 3, ArchetypeID = 2, SkillID = 4 },
                        new { ID = 4, ArchetypeID = 2, SkillID = 5 },
                        new { ID = 5, ArchetypeID = 3, SkillID = 2 },
                        new { ID = 6, ArchetypeID = 3, SkillID = 3 },
                        new { ID = 7, ArchetypeID = 4, SkillID = 2 },
                        new { ID = 8, ArchetypeID = 4, SkillID = 6 },
                        new { ID = 9, ArchetypeID = 1, SkillID = 6 }
                    );
                });

            modelBuilder.Entity("gorpsgen.Models.CharacterSheet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArchetypeID");

                    b.Property<int>("Dexterity");

                    b.Property<int>("Health");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Strength");

                    b.Property<string>("UserSub");

                    b.HasKey("ID");

                    b.HasIndex("ArchetypeID");

                    b.ToTable("CharacterSheets");
                });

            modelBuilder.Entity("gorpsgen.Models.CharacterSkill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CharacterSheetID");

                    b.Property<int>("PointsInvested");

                    b.Property<int>("SkillID");

                    b.HasKey("ID");

                    b.HasIndex("CharacterSheetID");

                    b.HasIndex("SkillID");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("gorpsgen.Models.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CombatAnswer");

                    b.Property<string>("MagicAnswer");

                    b.Property<int>("QuizId");

                    b.Property<string>("StealthAnswer");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new { ID = 1, CombatAnswer = "Draw your dagger, mercifully ending its life with a single thrust.", MagicAnswer = "Use herbs from your pack to put it to sleep.", QuizId = 1, StealthAnswer = "Do not interfere in the natural evolution of events, but rather take the opportunity to learn more about a strange animal you have never seen before.", Text = "Question 1: On a clear day you chance upon a strange animal, its leg trapped in a hunter's clawsnare. Judging from the bleeding it will not survive long." },
                        new { ID = 2, CombatAnswer = "Work in the forge with him casting iron for a new plow.", MagicAnswer = "Gather herbs for your mother who is preparing dinner.", QuizId = 1, StealthAnswer = "Go catch fish at the stream using a net and line.", Text = "Question 2: One Summer afternoon your father gives you a choice of chores." },
                        new { ID = 3, CombatAnswer = "Beat up your cousin, then tell him that if he ever calls you that nickname again, you will bloody him worse than this time.", MagicAnswer = "Make up a story that makes your nickname a badge of honor instead of something humiliating.", QuizId = 1, StealthAnswer = "Make up an even more embarrassing nickname for him and use it constantly until he learns his lesson.", Text = "Question 3: Your cousin has given you a very embarrassing nickname and, even worse, likes to call you it in front of your friends. You asked him to stop, but he finds it very amusing to watch you blush." },
                        new { ID = 4, CombatAnswer = "This is a terrible practice. A person's thoughts are his own and no one, not even a king, has the right to make such an invasion into another human's mind.", MagicAnswer = "Loyal followers to the king have nothing to fear from a Telepath. It is important to have a method of finding assassins and spies before it is too late.", QuizId = 1, StealthAnswer = "In these times, it is a necessary evil. Although you do not necessarily like the idea, a Telepath could have certain advantages during a time of war or in finding someone innocent of a crime.", Text = "Question 4: There is a lot of heated discussion at the local tavern over a grouped of people called 'Telepaths'. They have been hired by certain City-State kings. Rumor has it these Telepaths read a person's mind and tell their lord whether a follower is telling the truth or not." },
                        new { ID = 5, CombatAnswer = "Return to the store and give the shopkeeper his hard-earned money, explaining to him the mistake.", MagicAnswer = "Decide to put the extra money to good use and purchase items that would help your family.", QuizId = 1, StealthAnswer = "Pocket the extra money, knowing that shopkeepers in general tend to overcharge customers anyway.", Text = "Question 5: Your mother sends you to the market with a list of goods to buy. After you finish you find that by mistake a shopkeeper has given you too much money back in exchange for one of the items." },
                        new { ID = 6, CombatAnswer = "Pick up the bag and signal to the guard, knowing that the only honorable thing to do is return the money to its rightful owner.", MagicAnswer = "Leave the bag there, knowing that it is better not to get involved.", QuizId = 1, StealthAnswer = "Pick up the bag and pocket it, knowing that the extra windfall will help your family in times of trouble.", Text = "Question 6: While in the market place you witness a thief cut a purse from a noble. Even as he does so, the noble notices and calls for the city guards. In his haste to get away, the thief drops the purse near you. Surprisingly no one seems to notice the bag of coins at your feet." },
                        new { ID = 7, CombatAnswer = "Decline his offer, knowing that your father expects you to do the work, and it is better not to be in debt.", MagicAnswer = "Ask him to help you, knowing that two people can do the job faster than one, and agree to help him with one task of his choosing in the future.", QuizId = 1, StealthAnswer = "Accept his offer, reasoning that as long as the stables are cleaned, it matters not who does the cleaning.", Text = "Question 7: Your father sends you on a task which you loathe, cleaning the stables. On the way there, pitchfork in hand, you run into your friend from the homestead near your own. He offers to do it for you, in return for a future favor of his choosing." },
                        new { ID = 8, CombatAnswer = "Position yourself between the pipe and your mother.", MagicAnswer = "Grab the hot pipe and try to push it away.", QuizId = 1, StealthAnswer = "Push your mother out of the way.", Text = "Question 8: Your mother asks you to help fix the stove. While you are working, a very hot pipe slips its mooring and falls towards her." },
                        new { ID = 9, CombatAnswer = "Drop the sweetroll and step on it, then get ready for the fight.", MagicAnswer = "Give him the sweetroll now without argument, knowing that later this afternoon you will have all your friends with you and can come and take whatever he owes you.", QuizId = 1, StealthAnswer = "Act like you're going to give him the sweetroll, but at the last minute throw it in the air, hoping that they'll pay attention to it long enough for you to get a shot in on the leader.", Text = "Question 9: While in town the baker gives you a sweetroll. Delighted, you take it into an alley to enjoy only to be intercepted by a gang of three other kids your age. The leader demands the sweetroll, or else he and his friends will beat you and take it." },
                        new { ID = 10, CombatAnswer = "Rush to the town's aid immediately, despite your lack of knowledge of the circumstances.", MagicAnswer = "Stand aside and allow the man and the mob to pass, realizing it is probably best not to get involved.", QuizId = 1, StealthAnswer = "Rush to the man's aid immediately, despite your lack of knowledge of the circumstances.", Text = "Question 10: Entering town you find that you are witness to a very well-dressed man running from a crowd. He screams to you for help. The crowd behind him seem very angry." }
                    );
                });

            modelBuilder.Entity("gorpsgen.Models.Quiz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new { ID = 1, Title = "Sample character quiz" }
                    );
                });

            modelBuilder.Entity("gorpsgen.Models.QuizResponse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("QuizID");

                    b.Property<int>("RatioCombat");

                    b.Property<int>("RatioMagic");

                    b.Property<int>("RatioStealth");

                    b.Property<string>("UserSub");

                    b.HasKey("ID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizResponses");
                });

            modelBuilder.Entity("gorpsgen.Models.Skill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseStat");

                    b.Property<int?>("CharacterSheetID");

                    b.Property<string>("Difficulty");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("CharacterSheetID");

                    b.ToTable("Skills");

                    b.HasData(
                        new { ID = 1, BaseStat = "DX", Difficulty = "Average", Name = "Long Blade" },
                        new { ID = 2, BaseStat = "DX", Difficulty = "Average", Name = "Short Blade" },
                        new { ID = 3, BaseStat = "DX", Difficulty = "Average", Name = "Archery" },
                        new { ID = 4, BaseStat = "INT", Difficulty = "Hard", Name = "Conjuration" },
                        new { ID = 5, BaseStat = "INT", Difficulty = "Hard", Name = "Mysticism" },
                        new { ID = 6, BaseStat = "INT", Difficulty = "Easy", Name = "First Aid" }
                    );
                });

            modelBuilder.Entity("gorpsgen.Models.ArchetypeSkill", b =>
                {
                    b.HasOne("gorpsgen.Models.Archetype", "Archetype")
                        .WithMany()
                        .HasForeignKey("ArchetypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("gorpsgen.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gorpsgen.Models.CharacterSheet", b =>
                {
                    b.HasOne("gorpsgen.Models.Archetype", "Archetype")
                        .WithMany()
                        .HasForeignKey("ArchetypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gorpsgen.Models.CharacterSkill", b =>
                {
                    b.HasOne("gorpsgen.Models.CharacterSheet", "CharacterSheet")
                        .WithMany()
                        .HasForeignKey("CharacterSheetID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("gorpsgen.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gorpsgen.Models.Question", b =>
                {
                    b.HasOne("gorpsgen.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gorpsgen.Models.QuizResponse", b =>
                {
                    b.HasOne("gorpsgen.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gorpsgen.Models.Skill", b =>
                {
                    b.HasOne("gorpsgen.Models.CharacterSheet")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterSheetID");
                });
#pragma warning restore 612, 618
        }
    }
}
